apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  labels:
    app: mysql-db
    release: {{ .Release.Name }}  
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      release: {{ .Release.Name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: mysql-db
        release: {{ .Release.Name }}
    spec:
      initContainers:
      - name: configure-mysql
        image: busybox:stable # A simple image with sh/echo commands
        command: ['sh', '-c', 'echo "bind-address = 0.0.0.0" >> /mnt/config/my.cnf']
      containers:
        - name: mysql-db
          image: "{{ .Values.images.todo_db.repository }}:{{ .Values.images.todo_db.tag }}"
          imagePullPolicy: "{{ .Values.images.todo_db.pullPolicy }}"          
          ports:
            - name: api
              containerPort: {{ .Values.mysql.database_port }}
              protocol: TCP
          env:
            - name: MYSQL_DATABASE
              value: "{{ .Values.mysql.database_name }}"
            - name: MYSQL_ROOT_PASSWORD
              value: "{{ .Values.mysql.database_password }}"             
