apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-list
  labels:
    app: todo-list
    release: {{ .Release.Name }}  
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      release: {{ .Release.Name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: todo-list
        release: {{ .Release.Name }}
    spec:
      initContainers:
        - name: init-cont
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z todo-list-mysql 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL DB Server has started";']
      containers:
        - name: todo-list
          image: "{{ .Values.images.todo_backend.repository }}:{{ .Values.images.todo_backend.tag }}"
          imagePullPolicy: "{{ .Values.images.todo_backend.pullPolicy }}"
          ports:
            - name: api
              containerPort: 3000
              protocol: TCP
          env:
            - name: DATABASE_SVC
              value: todo-list-mysql
            - name: DATABASE_PORT
              value: "3306"
            - name: DATABASE_PASSWORD
              value: "{{ .Values.mysql.auth.rootPassword }}"  
        - name: todo-frontend
          image: "{{ .Values.images.todo_frontend.repository }}:{{ .Values.images.todo_frontend.tag }}"
          imagePullPolicy: "{{ .Values.images.todo_frontend.pullPolicy }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP             
