apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-list-ingress
spec:
  rules:
  - host: todo-list.ycinteclab.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        frontend:
          service:
            name: todo-list
            port:
              number: 80
