replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
images:
  todo_frontend: 
    repository: quay.io/ali.labiad/devops-repo/todo-frontend 
    pullPolicy: IfNotPresent
    tag: "latest"
  todo_backend: 
    repository: quay.io/ali.labiad/devops-repo/todo-backend 
    pullPolicy: IfNotPresent
    tag: "latest"
  todo_db: 
    repository: quay.io/ali.labiad/devops-repo/mysql 
    pullPolicy: IfNotPresent
    tag: "latest"

service:
  type: LoadBalancer
  port: 80

mysql:
  database_service: mysql-db
  database_name: todo
  database_password: secret-pass
  database_port: 3306
