replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
images:
  todo_frontend: 
    repository: quay.io/ali.labiad/devops-repo/todo-frontend 
    pullPolicy: IfNotPresent
    tag: "latest"
  todo_backend: 
    repository: quay.io/ali.labiad/devops-repo/todo-backend 
    pullPolicy: IfNotPresent
    tag: "latest"
  todo_db: 
    repository: quay.io/ali.labiad/devops-repo/mysql 
    pullPolicy: IfNotPresent
    tag: "latest"

service:
  type: ClusterIP
  port: 80

mysql:
  image:
    repository: bitnamilegacy/mysql
    tag: 8.0.30-debian-11-r27
  enabled: true
  auth:
    rootPassword: "secret-pass"
    database: "todo"
    username: "root"
    password: "secret-pass"
  persistence:
    enabled: true
    size: 1Gi
